export interface WordPair {
  wordA: string;
  wordB: string;
  category: string;
}

export const WORD_PAIRS: WordPair[] = [
  // Food and Drinks
  { category: "Food and Drinks", wordA: "Apple", wordB: "Pear" },
  { category: "Food and Drinks", wordA: "Pizza", wordB: "Focaccia" },
  { category: "Food and Drinks", wordA: "Milk", wordB: "Yogurt" },
  { category: "Food and Drinks", wordA: "Pasta", wordB: "Rice" },
  { category: "Food and Drinks", wordA: "Bread", wordB: "Cracker" },
  { category: "Food and Drinks", wordA: "Cheese", wordB: "Butter" },
  { category: "Food and Drinks", wordA: "Steak", wordB: "Sausage" },
  { category: "Food and Drinks", wordA: "Salmon", wordB: "Tuna" },
  { category: "Food and Drinks", wordA: "Scrambled Egg", wordB: "Hard-boiled Egg" },
  { category: "Food and Drinks", wordA: "Tomato", wordB: "Potato" },
  { category: "Food and Drinks", wordA: "Carrot", wordB: "Zucchini" },
  { category: "Food and Drinks", wordA: "Salad", wordB: "Spinach" },
  { category: "Food and Drinks", wordA: "Orange", wordB: "Grapefruit" },
  { category: "Food and Drinks", wordA: "Watermelon", wordB: "Cantaloupe" },
  { category: "Food and Drinks", wordA: "Strawberry", wordB: "Raspberry" },
  { category: "Food and Drinks", wordA: "Sugar", wordB: "Salt" },
  { category: "Food and Drinks", wordA: "Oil", wordB: "Vinegar" },
  { category: "Food and Drinks", wordA: "Red Wine", wordB: "White Wine" },
  { category: "Food and Drinks", wordA: "Water", wordB: "Fruit Juice" },
  { category: "Food and Drinks", wordA: "Cake", wordB: "Cookie" },
  { category: "Food and Drinks", wordA: "Dark Chocolate", wordB: "Milk Chocolate" },
  { category: "Food and Drinks", wordA: "Espresso Coffee", wordB: "Americano Coffee" },
  { category: "Food and Drinks", wordA: "Soup", wordB: "Broth" },
  { category: "Food and Drinks", wordA: "French Fries", wordB: "Potato Chips" },
  { category: "Food and Drinks", wordA: "Popcorn", wordB: "Nachos" },
  { category: "Food and Drinks", wordA: "Ketchup", wordB: "Mayonnaise" },
  { category: "Food and Drinks", wordA: "Lunch", wordB: "Dinner" },
  { category: "Food and Drinks", wordA: "Prosecco", wordB: "Champagne" },
  { category: "Food and Drinks", wordA: "Beer", wordB: "Wine" },
  { category: "Food and Drinks", wordA: "Spaghetti", wordB: "Ravioli" },
  { category: "Food and Drinks", wordA: "Parmesan", wordB: "Cheddar" },
  { category: "Food and Drinks", wordA: "Salami", wordB: "Pepperoni" },
  { category: "Food and Drinks", wordA: "Chicken", wordB: "Turkey" },
  { category: "Food and Drinks", wordA: "Honey", wordB: "Jam" },
  { category: "Food and Drinks", wordA: "Cappuccino", wordB: "Iced Coffee" },
  { category: "Food and Drinks", wordA: "Eggplant", wordB: "Bell Pepper" },
  { category: "Food and Drinks", wordA: "Coffee Maker", wordB: "Teapot" },
  { category: "Food and Drinks", wordA: "Risotto", wordB: "Fried Rice" },
  { category: "Food and Drinks", wordA: "Parsley", wordB: "Basil" },
  { category: "Food and Drinks", wordA: "Walnut", wordB: "Almond" },
  { category: "Food and Drinks", wordA: "Sugar", wordB: "Flour" },
  { category: "Food and Drinks", wordA: "Margarita", wordB: "Daiquiri" },
  { category: "Food and Drinks", wordA: "Grape", wordB: "Blueberry" },
  { category: "Food and Drinks", wordA: "Peach", wordB: "Apricot" },
  { category: "Food and Drinks", wordA: "Artichoke", wordB: "Asparagus" },
  { category: "Food and Drinks", wordA: "Coffee", wordB: "Tea" },
  { category: "Food and Drinks", wordA: "Sparkling Water", wordB: "Tonic Water" },
  { category: "Food and Drinks", wordA: "Clam", wordB: "Mussel" },
  { category: "Food and Drinks", wordA: "Orange Soda", wordB: "Lemonade" },
  { category: "Food and Drinks", wordA: "Baked Potato", wordB: "Mashed Potato" },
  { category: "Food and Drinks", wordA: "Donut", wordB: "Bagel" },
  { category: "Food and Drinks", wordA: "Almond", wordB: "Pistachio" },
  { category: "Food and Drinks", wordA: "Pepper", wordB: "Chili Pepper" },
  { category: "Food and Drinks", wordA: "Onion", wordB: "Garlic" },

  // Animals
  { category: "Animals", wordA: "Dog", wordB: "Cat" },
  { category: "Animals", wordA: "Dog", wordB: "Wolf" },
  { category: "Animals", wordA: "Horse", wordB: "Donkey" },
  { category: "Animals", wordA: "Cow", wordB: "Sheep" },
  { category: "Animals", wordA: "Pig", wordB: "Chicken" },
  { category: "Animals", wordA: "Lion", wordB: "Tiger" },
  { category: "Animals", wordA: "Elephant", wordB: "Giraffe" },
  { category: "Animals", wordA: "Monkey", wordB: "Gorilla" },
  { category: "Animals", wordA: "Parrot", wordB: "Canary" },
  { category: "Animals", wordA: "Penguin", wordB: "Seal" },
  { category: "Animals", wordA: "Snake", wordB: "Lizard" },
  { category: "Animals", wordA: "Spider", wordB: "Scorpion" },
  { category: "Animals", wordA: "Bee", wordB: "Wasp" },
  { category: "Animals", wordA: "Butterfly", wordB: "Dragonfly" },
  { category: "Animals", wordA: "Ant", wordB: "Ladybug" },
  { category: "Animals", wordA: "Dolphin", wordB: "Whale" },
  { category: "Animals", wordA: "Shark", wordB: "Orca" },
  { category: "Animals", wordA: "Crab", wordB: "Shrimp" },
  { category: "Animals", wordA: "Octopus", wordB: "Squid" },
  { category: "Animals", wordA: "Rabbit", wordB: "Squirrel" },
  { category: "Animals", wordA: "Mouse", wordB: "Rat" },
  { category: "Animals", wordA: "Frog", wordB: "Toad" },
  { category: "Animals", wordA: "Eagle", wordB: "Falcon" },
  { category: "Animals", wordA: "Mosquito", wordB: "Fly" },
  { category: "Animals", wordA: "Crow", wordB: "Pigeon" },
  { category: "Animals", wordA: "Jellyfish", wordB: "Starfish" },
  { category: "Animals", wordA: "Camel", wordB: "Llama" },
  { category: "Animals", wordA: "Cricket", wordB: "Grasshopper" },
  { category: "Animals", wordA: "Seagull", wordB: "Pigeon" },
  { category: "Animals", wordA: "Turtle", wordB: "Snail" },
  { category: "Animals", wordA: "Swallow", wordB: "Bat" },
  { category: "Animals", wordA: "Rhinoceros", wordB: "Hippopotamus" },
  { category: "Animals", wordA: "Feather", wordB: "Scale" },
  { category: "Animals", wordA: "Hedgehog", wordB: "Porcupine" },
  { category: "Animals", wordA: "Wasp", wordB: "Hornet" },

  // Objects
  { category: "Objects", wordA: "Chair", wordB: "Armchair" },
  { category: "Objects", wordA: "Book", wordB: "Comic Book" },
  { category: "Objects", wordA: "Bed", wordB: "Hammock" },
  { category: "Objects", wordA: "Fork", wordB: "Knife" },
  { category: "Objects", wordA: "Fork", wordB: "Spoon" },
  { category: "Objects", wordA: "Light Bulb", wordB: "Candle" },
  { category: "Objects", wordA: "Backpack", wordB: "Suitcase" },
  { category: "Objects", wordA: "Pen", wordB: "Pencil" },
  { category: "Objects", wordA: "Notebook", wordB: "Planner" },
  { category: "Objects", wordA: "Scissors", wordB: "Swiss Army Knife" },
  { category: "Objects", wordA: "Glue", wordB: "Adhesive Tape" },
  { category: "Objects", wordA: "Coin", wordB: "Banknote" },
  { category: "Objects", wordA: "Key", wordB: "Padlock" },
  { category: "Objects", wordA: "Hammer", wordB: "Screwdriver" },
  { category: "Objects", wordA: "Nail", wordB: "Screw" },
  { category: "Objects", wordA: "Glass", wordB: "Wine Glass" },
  { category: "Objects", wordA: "Frying Pan", wordB: "Pot" },
  { category: "Objects", wordA: "Oven", wordB: "Microwave" },
  { category: "Objects", wordA: "Ring", wordB: "Bracelet" },
  { category: "Objects", wordA: "Guitar", wordB: "Violin" },
  { category: "Objects", wordA: "Piano", wordB: "Organ" },
  { category: "Objects", wordA: "Flute", wordB: "Trumpet" },
  { category: "Objects", wordA: "Brush", wordB: "Spatula" },
  { category: "Objects", wordA: "Magnet", wordB: "Compass" },
  { category: "Objects", wordA: "Boot", wordB: "Loafer" },
  { category: "Objects", wordA: "Desk", wordB: "Table" },
  { category: "Objects", wordA: "Towel", wordB: "Bathrobe" },
  { category: "Objects", wordA: "Sheet", wordB: "Blanket" },
  { category: "Objects", wordA: "Tent", wordB: "Sleeping Bag" },
  { category: "Objects", wordA: "Mug", wordB: "Espresso Cup" },
  { category: "Objects", wordA: "Drum", wordB: "Cymbal" },
  { category: "Objects", wordA: "Thermometer", wordB: "Barometer" },
  { category: "Objects", wordA: "Flag", wordB: "Banner" },
  { category: "Objects", wordA: "Rug", wordB: "Carpet" },
  { category: "Objects", wordA: "Pillow", wordB: "Comforter" },
  { category: "Objects", wordA: "Rocking Chair", wordB: "Deck Chair" },
  { category: "Objects", wordA: "Doll", wordB: "Plushie" },
  { category: "Objects", wordA: "Arrow", wordB: "Dart" },
  { category: "Objects", wordA: "Bar of Soap", wordB: "Liquid Soap" },
  { category: "Objects", wordA: "Toothpaste", wordB: "Mouthwash" },
  { category: "Objects", wordA: "Saw", wordB: "Axe" },
  { category: "Objects", wordA: "Drill", wordB: "Screw Gun" },
  { category: "Objects", wordA: "Tissue", wordB: "Napkin" },
  { category: "Objects", wordA: "Necklace", wordB: "Earring" },
  { category: "Objects", wordA: "Stamp", wordB: "Sticker" },
  { category: "Objects", wordA: "Broom", wordB: "Mop" },
  { category: "Objects", wordA: "Chandelier", wordB: "Lamp" },
  { category: "Objects", wordA: "Nightstand", wordB: "Dresser" },
  { category: "Objects", wordA: "Pin", wordB: "Hair Clip" },
  { category: "Objects", wordA: "Bag", wordB: "Wallet" },
  { category: "Objects", wordA: "Binoculars", wordB: "Telescope" },
  { category: "Objects", wordA: "Bottle", wordB: "Flask" },
  { category: "Objects", wordA: "Ink", wordB: "Paint" },
  { category: "Objects", wordA: "Jar", wordB: "Can" },
  { category: "Objects", wordA: "Cutting Board", wordB: "Tray" },
  { category: "Objects", wordA: "Band-Aid", wordB: "Gauze" },
  { category: "Objects", wordA: "Lifebuoy", wordB: "Life Jacket" },
  { category: "Objects", wordA: "Rope", wordB: "Chain" },
  { category: "Objects", wordA: "Flashlight", wordB: "Lantern" },
  { category: "Objects", wordA: "Sponge", wordB: "Cloth" },
  { category: "Objects", wordA: "Door", wordB: "Window" },
  { category: "Objects", wordA: "Wall", wordB: "Fence" },
  { category: "Objects", wordA: "Floor", wordB: "Ceiling" },
  { category: "Objects", wordA: "Wardrobe", wordB: "Dresser" },
  { category: "Objects", wordA: "Blinds", wordB: "Curtains" },
  { category: "Objects", wordA: "Shoe", wordB: "Slipper" },
  { category: "Objects", wordA: "T-Shirt", wordB: "Tank Top" },
  { category: "Objects", wordA: "Sunglasses", wordB: "Eyeglasses" },
  { category: "Objects", wordA: "Watch", wordB: "Clock" },
  { category: "Objects", wordA: "Skirt", wordB: "Dress" },
  { category: "Objects", wordA: "Jacket", wordB: "Coat" },
  { category: "Objects", wordA: "Sock", wordB: "Stocking" },
  { category: "Objects", wordA: "Belt", wordB: "Suspenders" },
  { category: "Objects", wordA: "Shirt", wordB: "Polo Shirt" },
  { category: "Objects", wordA: "Pajamas", wordB: "Nightdress" },
  { category: "Objects", wordA: "Raincoat", wordB: "Umbrella" },
  { category: "Objects", wordA: "Swimsuit", wordB: "Underwear" },
  { category: "Objects", wordA: "Hoodie", wordB: "Sweater" },
  { category: "Objects", wordA: "Hat", wordB: "Cap" },
  { category: "Objects", wordA: "Bikini", wordB: "One-Piece Swimsuit" },
  { category: "Objects", wordA: "Cash", wordB: "Credit Card" },
  { category: "Objects", wordA: "Mirror", wordB: "Glass" },
  { category: "Objects", wordA: "Passport", wordB: "ID Card" },
  { category: "Objects", wordA: "Laptop", wordB: "Desktop" },
  { category: "Objects", wordA: "Perfume", wordB: "Deodorant" },
  { category: "Objects", wordA: "Letter", wordB: "Email" },
  { category: "Objects", wordA: "Wool", wordB: "Cotton" },
  { category: "Objects", wordA: "Scooter", wordB: "Bicycle" },
  { category: "Objects", wordA: "Airplane", wordB: "Helicopter" },
  { category: "Objects", wordA: "Keyboard", wordB: "Typewriter" },
  { category: "Objects", wordA: "Sailboat", wordB: "Speedboat" },
  { category: "Objects", wordA: "Train", wordB: "Subway" },
  { category: "Objects", wordA: "Balcony", wordB: "Terrace" },
  { category: "Objects", wordA: "Rose", wordB: "Tulip" },
  { category: "Objects", wordA: "Scooter", wordB: "Skateboard" },
  { category: "Objects", wordA: "Bus", wordB: "Tram" },
  { category: "Objects", wordA: "Swimming Pool", wordB: "Bathtub" },
  { category: "Objects", wordA: "Phone", wordB: "Tablet" },
  { category: "Objects", wordA: "Van", wordB: "Truck" },
  { category: "Objects", wordA: "Violin", wordB: "Cello" },
  { category: "Objects", wordA: "Car", wordB: "Motorcycle" },
  { category: "Objects", wordA: "Ship", wordB: "Ferry" },
  { category: "Objects", wordA: "Camper", wordB: "RV" },

  // Culture and Fun
  { category: "Culture and Fun", wordA: "Movie", wordB: "TV Series" },
  { category: "Culture and Fun", wordA: "Photo", wordB: "Video" },
  { category: "Culture and Fun", wordA: "News", wordB: "Gossip" },
  { category: "Culture and Fun", wordA: "Internet", wordB: "Television" },
  { category: "Culture and Fun", wordA: "Facebook", wordB: "Instagram" },
  { category: "Culture and Fun", wordA: "Netflix", wordB: "Hulu" },
  { category: "Culture and Fun", wordA: "Harry Potter", wordB: "Lord of the Rings" },
  { category: "Culture and Fun", wordA: "News", wordB: "Documentary" },
  { category: "Culture and Fun", wordA: "Cartoon", wordB: "Caricature" },
  { category: "Culture and Fun", wordA: "Diary", wordB: "Blog" },
  { category: "Culture and Fun", wordA: "Comedy", wordB: "Tragedy" },
  { category: "Culture and Fun", wordA: "Puppet", wordB: "Doll" },
  { category: "Culture and Fun", wordA: "Tennis", wordB: "Badminton" },
  { category: "Culture and Fun", wordA: "Soccer", wordB: "Rugby" },
  { category: "Culture and Fun", wordA: "Sailing", wordB: "Surfing" },
  { category: "Culture and Fun", wordA: "Chess", wordB: "Checkers" },
  { category: "Culture and Fun", wordA: "Basketball", wordB: "Volleyball" },
  { category: "Culture and Fun", wordA: "Skiing", wordB: "Snowboarding" },
  { category: "Culture and Fun", wordA: "Ice Skating", wordB: "Hockey" },
  { category: "Culture and Fun", wordA: "Monopoly", wordB: "Risk" },
  { category: "Culture and Fun", wordA: "Crossword", wordB: "Sudoku" },
  { category: "Culture and Fun", wordA: "Pool", wordB: "Darts" },
  { category: "Culture and Fun", wordA: "Singing", wordB: "Dancing" },
  { category: "Culture and Fun", wordA: "Ghost", wordB: "Zombie" },
  { category: "Culture and Fun", wordA: "Wizard", wordB: "Witch" },
  { category: "Culture and Fun", wordA: "Fairy", wordB: "Elf" },
  { category: "Culture and Fun", wordA: "Sword", wordB: "Dagger" },
  { category: "Culture and Fun", wordA: "Castle", wordB: "Cave" },
  { category: "Culture and Fun", wordA: "Treasure", wordB: "Gold" },
  { category: "Culture and Fun", wordA: "Pirate", wordB: "Ninja" },
  { category: "Culture and Fun", wordA: "Robot", wordB: "Alien" },
  { category: "Culture and Fun", wordA: "Superhero", wordB: "Villain" },
  { category: "Culture and Fun", wordA: "Myth", wordB: "Fable" },
  { category: "Culture and Fun", wordA: "Armor", wordB: "Helmet" },
  { category: "Culture and Fun", wordA: "Bow", wordB: "Crossbow" },
  { category: "Culture and Fun", wordA: "Mask", wordB: "Disguise" },
  { category: "Culture and Fun", wordA: "Puzzle", wordB: "Riddle" },
  { category: "Culture and Fun", wordA: "King", wordB: "Queen" },
  { category: "Culture and Fun", wordA: "Novel", wordB: "Short Story" },
  { category: "Culture and Fun", wordA: "Newspaper", wordB: "Magazine" },
  { category: "Culture and Fun", wordA: "Painting", wordB: "Drawing" },
  { category: "Culture and Fun", wordA: "Trip", wordB: "Vacation" },
  { category: "Culture and Fun", wordA: "Carnival", wordB: "Halloween" },
  { category: "Culture and Fun", wordA: "Diploma", wordB: "Trophy" },
  { category: "Culture and Fun", wordA: "Clue", wordB: "Evidence" },
  { category: "Culture and Fun", wordA: "Anthem", wordB: "Song" },
  { category: "Culture and Fun", wordA: "Anthem", wordB: "Prayer" },
  { category: "Culture and Fun", wordA: "Anecdote", wordB: "Joke" },
  { category: "Culture and Fun", wordA: "Mosaic", wordB: "Stained Glass" },
  { category: "Culture and Fun", wordA: "Cinema", wordB: "Theater" },
  { category: "Culture and Fun", wordA: "School", wordB: "University" },
  { category: "Culture and Fun", wordA: "Library", wordB: "Bookstore" },
  { category: "Culture and Fun", wordA: "Rhythm", wordB: "Melody" },

  // Abstract Concepts
  { category: "Abstract Concepts", wordA: "History", wordB: "Legend" },
  { category: "Abstract Concepts", wordA: "Math", wordB: "Science" },
  { category: "Abstract Concepts", wordA: "Work", wordB: "Hobby" },
  { category: "Abstract Concepts", wordA: "Dream", wordB: "Nightmare" },
  { category: "Abstract Concepts", wordA: "Question", wordB: "Answer" },
  { category: "Abstract Concepts", wordA: "Lie", wordB: "Truth" },
  { category: "Abstract Concepts", wordA: "Gift", wordB: "Surprise" },
  { category: "Abstract Concepts", wordA: "Goal", wordB: "Mission" },
  { category: "Abstract Concepts", wordA: "Luck", wordB: "Fate" },
  { category: "Abstract Concepts", wordA: "Light", wordB: "Shadow" },
  { category: "Abstract Concepts", wordA: "Mistake", wordB: "Solution" },
  { category: "Abstract Concepts", wordA: "Rule", wordB: "Law" },
  { category: "Abstract Concepts", wordA: "Hot", wordB: "Cold" },
  { category: "Abstract Concepts", wordA: "Hunger", wordB: "Thirst" },
  { category: "Abstract Concepts", wordA: "Laughter", wordB: "Crying" },
  { category: "Abstract Concepts", wordA: "Pain", wordB: "Pleasure" },
  { category: "Abstract Concepts", wordA: "Fear", wordB: "Courage" },
  { category: "Abstract Concepts", wordA: "Happiness", wordB: "Sadness" },
  { category: "Abstract Concepts", wordA: "Anger", wordB: "Calm" },
  { category: "Abstract Concepts", wordA: "Paradise", wordB: "Hell" },
  { category: "Abstract Concepts", wordA: "Magic", wordB: "Illusion" },
  { category: "Abstract Concepts", wordA: "Poetry", wordB: "Prose" },
  { category: "Abstract Concepts", wordA: "Noise", wordB: "Sound" },
  { category: "Abstract Concepts", wordA: "Love", wordB: "Friendship" },
  { category: "Abstract Concepts", wordA: "Destiny", wordB: "Chance" },
  { category: "Abstract Concepts", wordA: "Science", wordB: "Philosophy" },
  { category: "Abstract Concepts", wordA: "Nostalgia", wordB: "Regret" },
  { category: "Abstract Concepts", wordA: "Cause", wordB: "Effect" },
  { category: "Abstract Concepts", wordA: "Theory", wordB: "Practice" },
  { category: "Abstract Concepts", wordA: "Talent", wordB: "Skill" },
  { category: "Abstract Concepts", wordA: "Memory", wordB: "Promise" },
  { category: "Abstract Concepts", wordA: "Doubt", wordB: "Belief" },
  { category: "Abstract Concepts", wordA: "Instinct", wordB: "Reason" },
  { category: "Abstract Concepts", wordA: "Peace", wordB: "Silence" },
  { category: "Abstract Concepts", wordA: "Pride", wordB: "Shame" },
  { category: "Abstract Concepts", wordA: "Honor", wordB: "Duty" },
  { category: "Abstract Concepts", wordA: "Victory", wordB: "Conquest" },
  { category: "Abstract Concepts", wordA: "Secret", wordB: "Mystery" },
  { category: "Abstract Concepts", wordA: "Faith", wordB: "Hope" },
  { category: "Abstract Concepts", wordA: "Gossip", wordB: "News" },
  { category: "Abstract Concepts", wordA: "Instinct", wordB: "Intuition" },
  { category: "Abstract Concepts", wordA: "Knowledge", wordB: "Wisdom" },
  { category: "Abstract Concepts", wordA: "Vice", wordB: "Sin" },
  { category: "Abstract Concepts", wordA: "Summer", wordB: "Winter" },
  { category: "Abstract Concepts", wordA: "Word", wordB: "Number" },
  { category: "Abstract Concepts", wordA: "Brother", wordB: "Sister" },
  { category: "Abstract Concepts", wordA: "Run", wordB: "Walk" },
  { category: "Abstract Concepts", wordA: "Proverb", wordB: "Idiom" },

  // Mixed
  { category: "Mixed", wordA: "Password", wordB: "PIN" },
  { category: "Mixed", wordA: "City", wordB: "Village" },
  { category: "Mixed", wordA: "Applause", wordB: "Whistle" },
  { category: "Mixed", wordA: "Tattoo", wordB: "Scar" },
  { category: "Mixed", wordA: "Signature", wordB: "Initials" },
  { category: "Mixed", wordA: "Dawn", wordB: "Sunset" },
  { category: "Mixed", wordA: "Fire", wordB: "Ice" },
  { category: "Mixed", wordA: "Morning", wordB: "Afternoon" },
  { category: "Mixed", wordA: "Hand", wordB: "Foot" },
  { category: "Mixed", wordA: "Eye", wordB: "Ear" },
  { category: "Mixed", wordA: "Nose", wordB: "Mouth" },
  { category: "Mixed", wordA: "Hair", wordB: "Beard" },
  { category: "Mixed", wordA: "Heart", wordB: "Brain" },
  { category: "Mixed", wordA: "Feather", wordB: "Fur" },
  { category: "Mixed", wordA: "Levee", wordB: "Dam" },
  { category: "Mixed", wordA: "Stone", wordB: "Rock" },
  { category: "Mixed", wordA: "Ice", wordB: "Frost" },
  { category: "Mixed", wordA: "Doctor", wordB: "Nurse" },
  { category: "Mixed", wordA: "Garden", wordB: "Orchard" },
  { category: "Mixed", wordA: "Basement", wordB: "Attic" },
  { category: "Mixed", wordA: "Roundabout", wordB: "Intersection" },
  { category: "Mixed", wordA: "Hotel", wordB: "Hostel" },
  { category: "Mixed", wordA: "Bridge", wordB: "Tunnel" },
  { category: "Mixed", wordA: "Teacher", wordB: "Professor" },
  { category: "Mixed", wordA: "Sun", wordB: "Moon" },
  { category: "Mixed", wordA: "Architect", wordB: "Engineer" },
  { category: "Mixed", wordA: "Dust", wordB: "Ash" },
  { category: "Mixed", wordA: "Church", wordB: "Mosque" },
  { category: "Mixed", wordA: "Doctor", wordB: "Veterinarian" },
  { category: "Mixed", wordA: "Pharmacy", wordB: "Hospital" },
  { category: "Mixed", wordA: "Hail", wordB: "Sleet" },
  { category: "Mixed", wordA: "Mars", wordB: "Jupiter" },
  { category: "Mixed", wordA: "Skyscraper", wordB: "Building" },
  { category: "Mixed", wordA: "Hut", wordB: "Bungalow" },
  { category: "Mixed", wordA: "Glacier", wordB: "Avalanche" },
  { category: "Mixed", wordA: "Star", wordB: "Planet" },
  { category: "Mixed", wordA: "Referee", wordB: "Judge" },
  { category: "Mixed", wordA: "Singer", wordB: "Musician" },
  { category: "Mixed", wordA: "Island", wordB: "Peninsula" },
  { category: "Mixed", wordA: "Station", wordB: "Airport" },
  { category: "Mixed", wordA: "Lawn", wordB: "Field" },
  { category: "Mixed", wordA: "Grass", wordB: "Leaf" },
  { category: "Mixed", wordA: "Beach", wordB: "Cliff" },
  { category: "Mixed", wordA: "Restaurant", wordB: "Bar" },
  { category: "Mixed", wordA: "Police Officer", wordB: "Firefighter" },
  { category: "Mixed", wordA: "Judge", wordB: "Lawyer" },
  { category: "Mixed", wordA: "Forest", wordB: "Jungle" },
  { category: "Mixed", wordA: "Hurricane", wordB: "Tornado" },
  { category: "Mixed", wordA: "Chef", wordB: "Waiter" },
  { category: "Mixed", wordA: "Pilot", wordB: "Driver" },
  { category: "Mixed", wordA: "Warehouse", wordB: "Cellar" },
  { category: "Mixed", wordA: "Tide", wordB: "Current" },
  { category: "Mixed", wordA: "Road", wordB: "Highway" },
  { category: "Mixed", wordA: "Thunder", wordB: "Lightning" },
  { category: "Mixed", wordA: "Artisan", wordB: "Worker" },
  { category: "Mixed", wordA: "Emperor", wordB: "Pharaoh" },
  { category: "Mixed", wordA: "Prison", wordB: "Asylum" },
  { category: "Mixed", wordA: "Captain", wordB: "Commander" },
  { category: "Mixed", wordA: "Painter", wordB: "Sculptor" },
  { category: "Mixed", wordA: "Shop", wordB: "Workshop" },
  { category: "Mixed", wordA: "Rain", wordB: "Snow" },
  { category: "Mixed", wordA: "Mime", wordB: "Clown" },
  { category: "Mixed", wordA: "River", wordB: "Lake" },
  { category: "Mixed", wordA: "Barber", wordB: "Hairdresser" },
  { category: "Mixed", wordA: "Prince", wordB: "Knight" },
  { category: "Mixed", wordA: "Volcano", wordB: "Earthquake" },
  { category: "Mixed", wordA: "Writer", wordB: "Journalist" },
  { category: "Mixed", wordA: "Mayor", wordB: "President" },
  { category: "Mixed", wordA: "Mountain", wordB: "Hill" },
  { category: "Mixed", wordA: "Cave", wordB: "Mine" },
  { category: "Mixed", wordA: "Well", wordB: "Fountain" },
  { category: "Mixed", wordA: "Square", wordB: "Park" },
  { category: "Mixed", wordA: "Firefighter", wordB: "Forest Ranger" },
  { category: "Mixed", wordA: "Soldier", wordB: "Mercenary" },
  { category: "Mixed", wordA: "Butler", wordB: "Chauffeur" },
  { category: "Mixed", wordA: "Museum", wordB: "Art Gallery" },
  { category: "Mixed", wordA: "Lighthouse", wordB: "Tower" },
  { category: "Mixed", wordA: "Factory", wordB: "Power Plant" },
  { category: "Mixed", wordA: "Stream", wordB: "Creek" },
  { category: "Mixed", wordA: "Actor", wordB: "Director" },
  { category: "Mixed", wordA: "Ocean", wordB: "Sea" },
  { category: "Mixed", wordA: "Path", wordB: "Stairs" },
  { category: "Mixed", wordA: "Sand", wordB: "Gravel" },
  { category: "Mixed", wordA: "Cloud", wordB: "Fog" },
  { category: "Mixed", wordA: "Alley", wordB: "Avenue" },
  { category: "Mixed", wordA: "Supermarket", wordB: "Shopping Mall" },
  { category: "Mixed", wordA: "Hospital", wordB: "Clinic" },
  { category: "Mixed", wordA: "Waterfall", wordB: "Spring" },
  { category: "Mixed", wordA: "King", wordB: "Pope" },
  { category: "Mixed", wordA: "Spy", wordB: "Detective" },
  { category: "Mixed", wordA: "Captain", wordB: "General" },
  { category: "Mixed", wordA: "Army", wordB: "Navy" },
];

export function pickRandomPair(): WordPair {
  return WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)];
}
