export interface WordPair { wordA: string; wordB: string; category: string; }

export const WORD_PAIRS: WordPair[] = [
  // Food & Drinks
  { category: "Food & Drinks", wordA: "Pizza", wordB: "Focaccia" },
  { category: "Food & Drinks", wordA: "Coffee", wordB: "Tea" },
  { category: "Food & Drinks", wordA: "Cake", wordB: "Cookie" },
  { category: "Food & Drinks", wordA: "Beer", wordB: "Wine" },
  { category: "Food & Drinks", wordA: "Pasta", wordB: "Rice" },
  { category: "Food & Drinks", wordA: "Steak", wordB: "Sausage" },
  { category: "Food & Drinks", wordA: "Apple", wordB: "Pear" },
  { category: "Food & Drinks", wordA: "Bread", wordB: "Cracker" },
  { category: "Food & Drinks", wordA: "Salmon", wordB: "Tuna" },
  { category: "Food & Drinks", wordA: "Orange", wordB: "Grapefruit" },
  { category: "Food & Drinks", wordA: "Milk", wordB: "Yogurt" },
  { category: "Food & Drinks", wordA: "Strawberry", wordB: "Raspberry" },
  { category: "Food & Drinks", wordA: "Dark Chocolate", wordB: "Milk Chocolate" },
  { category: "Food & Drinks", wordA: "French Fries", wordB: "Potato Chips" },
  { category: "Food & Drinks", wordA: "Ketchup", wordB: "Mayonnaise" },
  { category: "Food & Drinks", wordA: "Scrambled Egg", wordB: "Hard-boiled Egg" },
  { category: "Food & Drinks", wordA: "Cappuccino", wordB: "Iced Coffee" },
  { category: "Food & Drinks", wordA: "Spaghetti", wordB: "Ravioli" },
  { category: "Food & Drinks", wordA: "Red Wine", wordB: "White Wine" },
  { category: "Food & Drinks", wordA: "Donut", wordB: "Bagel" },
  { category: "Food & Drinks", wordA: "Salad", wordB: "Spinach" },
  { category: "Food & Drinks", wordA: "Watermelon", wordB: "Cantaloupe" },
  { category: "Food & Drinks", wordA: "Honey", wordB: "Jam" },
  { category: "Food & Drinks", wordA: "Onion", wordB: "Garlic" },
  { category: "Food & Drinks", wordA: "Chicken", wordB: "Turkey" },

  // Animals
  { category: "Animals", wordA: "Dog", wordB: "Cat" },
  { category: "Animals", wordA: "Dog", wordB: "Wolf" },
  { category: "Animals", wordA: "Lion", wordB: "Tiger" },
  { category: "Animals", wordA: "Dolphin", wordB: "Whale" },
  { category: "Animals", wordA: "Parrot", wordB: "Canary" },
  { category: "Animals", wordA: "Snake", wordB: "Lizard" },
  { category: "Animals", wordA: "Bee", wordB: "Wasp" },
  { category: "Animals", wordA: "Eagle", wordB: "Falcon" },
  { category: "Animals", wordA: "Elephant", wordB: "Giraffe" },
  { category: "Animals", wordA: "Shark", wordB: "Orca" },
  { category: "Animals", wordA: "Rabbit", wordB: "Squirrel" },
  { category: "Animals", wordA: "Penguin", wordB: "Seal" },
  { category: "Animals", wordA: "Butterfly", wordB: "Dragonfly" },
  { category: "Animals", wordA: "Octopus", wordB: "Squid" },
  { category: "Animals", wordA: "Frog", wordB: "Toad" },
  { category: "Animals", wordA: "Camel", wordB: "Llama" },
  { category: "Animals", wordA: "Mouse", wordB: "Rat" },
  { category: "Animals", wordA: "Crow", wordB: "Pigeon" },
  { category: "Animals", wordA: "Horse", wordB: "Donkey" },
  { category: "Animals", wordA: "Monkey", wordB: "Gorilla" },
  { category: "Animals", wordA: "Spider", wordB: "Scorpion" },
  { category: "Animals", wordA: "Crab", wordB: "Shrimp" },
  { category: "Animals", wordA: "Turtle", wordB: "Snail" },
  { category: "Animals", wordA: "Rhinoceros", wordB: "Hippopotamus" },
  { category: "Animals", wordA: "Hedgehog", wordB: "Porcupine" },

  // Objects
  { category: "Objects", wordA: "Chair", wordB: "Armchair" },
  { category: "Objects", wordA: "Book", wordB: "Comic Book" },
  { category: "Objects", wordA: "Pen", wordB: "Pencil" },
  { category: "Objects", wordA: "Guitar", wordB: "Violin" },
  { category: "Objects", wordA: "Watch", wordB: "Clock" },
  { category: "Objects", wordA: "Hammer", wordB: "Screwdriver" },
  { category: "Objects", wordA: "Mug", wordB: "Espresso Cup" },
  { category: "Objects", wordA: "Mirror", wordB: "Glass" },
  { category: "Objects", wordA: "Backpack", wordB: "Suitcase" },
  { category: "Objects", wordA: "Phone", wordB: "Tablet" },
  { category: "Objects", wordA: "Laptop", wordB: "Desktop" },
  { category: "Objects", wordA: "Raincoat", wordB: "Umbrella" },
  { category: "Objects", wordA: "Car", wordB: "Motorcycle" },
  { category: "Objects", wordA: "Airplane", wordB: "Helicopter" },
  { category: "Objects", wordA: "Rose", wordB: "Tulip" },
  { category: "Objects", wordA: "Fork", wordB: "Spoon" },
  { category: "Objects", wordA: "Light Bulb", wordB: "Candle" },
  { category: "Objects", wordA: "Oven", wordB: "Microwave" },
  { category: "Objects", wordA: "Tent", wordB: "Sleeping Bag" },
  { category: "Objects", wordA: "Drum", wordB: "Cymbal" },
  { category: "Objects", wordA: "Broom", wordB: "Mop" },
  { category: "Objects", wordA: "Towel", wordB: "Bathrobe" },
  { category: "Objects", wordA: "Key", wordB: "Padlock" },
  { category: "Objects", wordA: "Scooter", wordB: "Bicycle" },
  { category: "Objects", wordA: "Passport", wordB: "ID Card" },

  // Culture & Fun
  { category: "Culture", wordA: "Movie", wordB: "TV Series" },
  { category: "Culture", wordA: "Soccer", wordB: "Rugby" },
  { category: "Culture", wordA: "Chess", wordB: "Checkers" },
  { category: "Culture", wordA: "Tennis", wordB: "Badminton" },
  { category: "Culture", wordA: "Pirate", wordB: "Ninja" },
  { category: "Culture", wordA: "Ghost", wordB: "Zombie" },
  { category: "Culture", wordA: "Superhero", wordB: "Villain" },
  { category: "Culture", wordA: "Wizard", wordB: "Witch" },
  { category: "Culture", wordA: "King", wordB: "Queen" },
  { category: "Culture", wordA: "Singing", wordB: "Dancing" },
  { category: "Culture", wordA: "Basketball", wordB: "Volleyball" },
  { category: "Culture", wordA: "Painting", wordB: "Drawing" },
  { category: "Culture", wordA: "Cinema", wordB: "Theater" },
  { category: "Culture", wordA: "Robot", wordB: "Alien" },
  { category: "Culture", wordA: "Skiing", wordB: "Snowboarding" },
  { category: "Culture", wordA: "Harry Potter", wordB: "Lord of the Rings" },
  { category: "Culture", wordA: "Puzzle", wordB: "Riddle" },
  { category: "Culture", wordA: "Carnival", wordB: "Halloween" },
  { category: "Culture", wordA: "Pool", wordB: "Darts" },
  { category: "Culture", wordA: "Ice Skating", wordB: "Hockey" },

  // Abstract
  { category: "Abstract", wordA: "Dream", wordB: "Nightmare" },
  { category: "Abstract", wordA: "Lie", wordB: "Truth" },
  { category: "Abstract", wordA: "Light", wordB: "Shadow" },
  { category: "Abstract", wordA: "Fear", wordB: "Courage" },
  { category: "Abstract", wordA: "Love", wordB: "Friendship" },
  { category: "Abstract", wordA: "Hot", wordB: "Cold" },
  { category: "Abstract", wordA: "Summer", wordB: "Winter" },
  { category: "Abstract", wordA: "Secret", wordB: "Mystery" },
  { category: "Abstract", wordA: "Luck", wordB: "Fate" },
  { category: "Abstract", wordA: "Magic", wordB: "Illusion" },
  { category: "Abstract", wordA: "Happiness", wordB: "Sadness" },
  { category: "Abstract", wordA: "Question", wordB: "Answer" },
  { category: "Abstract", wordA: "Victory", wordB: "Conquest" },
  { category: "Abstract", wordA: "Knowledge", wordB: "Wisdom" },
  { category: "Abstract", wordA: "Noise", wordB: "Sound" },

  // Mixed
  { category: "Mixed", wordA: "Doctor", wordB: "Nurse" },
  { category: "Mixed", wordA: "Sun", wordB: "Moon" },
  { category: "Mixed", wordA: "Fire", wordB: "Ice" },
  { category: "Mixed", wordA: "Mountain", wordB: "Hill" },
  { category: "Mixed", wordA: "Rain", wordB: "Snow" },
  { category: "Mixed", wordA: "Ocean", wordB: "Sea" },
  { category: "Mixed", wordA: "Forest", wordB: "Jungle" },
  { category: "Mixed", wordA: "Police Officer", wordB: "Firefighter" },
  { category: "Mixed", wordA: "Teacher", wordB: "Professor" },
  { category: "Mixed", wordA: "Spy", wordB: "Detective" },
  { category: "Mixed", wordA: "River", wordB: "Lake" },
  { category: "Mixed", wordA: "Hotel", wordB: "Hostel" },
  { category: "Mixed", wordA: "Thunder", wordB: "Lightning" },
  { category: "Mixed", wordA: "Chef", wordB: "Waiter" },
  { category: "Mixed", wordA: "Museum", wordB: "Art Gallery" },
];
